<a href="https://colab.research.google.com/github/dinarojasocho-oss/LAB.-COLAB.02/blob/main/LAB_D4_FGD_PSAYAN_2026_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **LABORATORIO DIRIGIDO N° 04**
## **Fundamentos de Gestión de Datos**
### Semana 4 — Normalización de Bases de Datos y Consultas SQL Básicas

---

**Docente:** Pilar Rocío Sayán Mejía &nbsp;|&nbsp; **Semestre:** 2026-I &nbsp;|&nbsp; **Modalidad:** Individual — 2 horas

**Entregable:** Notebook `.ipynb` ejecutado con código, resultados visibles y respuestas completas

---

| Campo | Completa aquí |
|---|---|
| Nombre completo | |
| Sección | |
| Fecha | |

---
## I. Elemento de la Capacidad Terminal

Identifica violaciones a la Primera, Segunda y Tercera Forma Normal en una tabla desnormalizada, interpreta el modelo Entidad-Relación de la panadería Dulce Migaja e implementa consultas SQL básicas sobre la base de datos normalizada en SQLite, relacionando el diseño relacional con decisiones de negocio reales.

---
## Caso de Negocio: La Panadería Dulce Migaja

**Dulce Migaja** es una pequeña cadena de panaderías artesanales con varios locales en la ciudad. Durante años, el dueño registró todas sus ventas en una sola tabla llamada `ventas_original`. En esa tabla, cada fila repetía el nombre completo del cliente, el nombre del producto, la categoría y el local donde se realizó la venta.

Por ejemplo, si el cliente Carlos Quispe compraba pan de molde tres veces en el mismo mes, su nombre y teléfono aparecían repetidos en tres filas distintas. Cuando el dueño quería corregir un dato —como el nombre de un local— tenía que buscar y actualizar cada fila manualmente, lo que generaba errores e inconsistencias.

Para resolver este problema, el equipo normalizó la base de datos separando la información en tablas independientes: `categorias`, `productos`, `clientes`, `locales` y `ventas`. Ahora cada dato se guarda una sola vez y las tablas se conectan mediante claves foráneas.

> **Tu rol:** Eres el analista de datos de Dulce Migaja. Primero explorarás la tabla original para entender el problema, luego trabajarás con las tablas normalizadas para ver la solución y responderás preguntas del equipo directivo.

---
## **ACTIVIDAD 1: Revisión de Conceptos**

> Completa la siguiente tabla con **tus propias palabras**. No copies textualmente del material de clase. Usa el caso Dulce Migaja como referencia para los ejemplos.

| Concepto | Definición con tus palabras | Ejemplo del caso Dulce Migaja |
|---|---|---|
| Primera Forma Normal (1FN) |Cada celda debe tener un solo dato. |No guardar “Pan, Café, Jugo” en una sola celda, sino un producto por fila. |
| Segunda Forma Normal (2FN) |Cada dato debe depender de la clave correcta de su tabla. |El precio del producto debe estar en productos, no repetido en cada venta.|
| Tercera Forma Normal (3FN) |Evita guardar datos que dependen de otra tabla. |El nombre de la categoría va en categorias, y productos solo guarda id_categoria.|
| Dependencia parcial |Cuando un dato depende solo de una parte de la clave. | El nombre del producto depende de id_producto, no de toda la venta.|
| Dependencia transitiva |Cuando un dato depende de otro dato que no es clave. |nombre_categoria depende de la categoría, no del producto. |
| Clave Primaria (PK) |Identifica una fila de forma única. |id_cliente identifica a cada cliente. |
| Clave Foránea (FK) |Conecta una tabla con otra.|id_cliente en ventas conecta con clientes. |
| Cardinalidad 1:N |Un registro puede relacionarse con varios registros de otra tabla. |Un cliente puede tener muchas ventas. |
| Redundancia de datos |Repetir el mismo dato muchas veces. |Repetir “Ana Torres” en varias ventas. |

**Responde las siguientes preguntas con tus propias palabras:**

**Pregunta 1:**
¿Qué es la normalización y qué tres problemas concretos resuelve en la panadería Dulce Migaja?

Respuesta:
_La normalización es el proceso de organizar de una base de datos en varias tablas relacionadas para evitar repetir información. En Dulce Migaja resuelve tres problemas: reduce la repetición de datos, evita errores al actualizar y mejora el orden de la base de datos._

**Pregunta 2:**
¿Cuál es la diferencia entre una clave primaria (PK) y una clave foránea (FK)? Da un ejemplo con dos tablas de Dulce Migaja.

Respuesta:
_Una clave primaria permite identificar de forma única cada registro de una tabla. Por ejemplo, id_cliente identifica a cada cliente en la tabla clientes. Una clave foránea sirve para conectar una tabla con otra. Ejemplo, id_cliente en la tabla ventas permite saber qué cliente realizó una compra._
**Pregunta 3:**
En la tabla `ventas_original`, el nombre y teléfono del cliente se repiten en cada fila de venta. ¿Qué forma normal se viola? ¿Qué ocurre si el cliente cambia su número de teléfono?

Respuesta:
_Se genera redundancia de datos y se afecta la normalización porque el dato del cliente se repite en varias filas. Si el cliente cambia su número de teléfono, el administrador tendría que actualizarlo. Esto puede generar errores si alguna fila no se actualiza correctamente._

**Pregunta 4:**
¿Por qué en el modelo normalizado la tabla `ventas` solo guarda `id_cliente` en lugar del nombre completo del cliente?

Respuesta:
_Porque en el modelo normalizado de los datos, el cliente se guardan en la tabla clientes. La tabla ventas solo necesita guardar id_cliente para conectarse con esa tabla. Esto evita repetir el nombre completo del cliente en cada venta y permite actualizar sus datos en un solo lugar._

---
## **ACTIVIDAD 2: Exploración con SQLite**

En esta actividad explorarás la base de datos real de Dulce Migaja. La base de datos se descarga automáticamente desde GitHub. Ejecuta cada celda en orden y responde las preguntas después de observar el resultado.

### Relación entre las tablas

Antes de ejecutar las consultas, observa cómo se relacionan las tablas normalizadas:

```
clientes (id_cliente PK) ──────────────────┐
                                             │
productos (id_producto PK) ──────────────── ventas (id_venta PK)
                                             │
locales (id_local PK) ─────────────────────┘
    │
    └── categorias (id_categoria PK) → productos.id_categoria FK
```


> Esta actividad busca que interpreten la lógica del diseño relacional y comprendan cómo la normalización ayuda a evitar redundancia e inconsistencias en los datos.

### 🔎 Pregunta de interpretación

Interpreten el siguiente modelo Entidad–Relación (ER) del minimarket:  
https://dbdiagram.io/d/6a15efbab62396d22c76dd82

Expliquen:
- cómo se relacionan las tablas entre sí,
- cuál es la función de las claves primarias (PK) y claves foráneas (FK),
- y por qué este diseño normalizado ayuda a evitar redundancia de datos y problemas de actualización en el negocio.

![Untitled.svg]()

### **Paso 0: Descargar la base de datos desde GitHub y conectarse**

Ejecuta esta celda primero. Descarga la base de datos de Dulce Migaja directamente desde el repositorio de GitHub y abre la conexión con SQLite.

In [ ]:
import sqlite3
import pandas as pd
import subprocess
from pathlib import Path

# Descargar la base de datos desde GitHub
url = (
    'https://raw.githubusercontent.com/Rociosayan/'
    'PMD1_Fundamentos_Gestion_Datos/main/casos/'
    '17_panaderia_normalizacion/panaderia_normalizacion.db'
)
db_path = Path('panaderia_normalizacion.db')

# Se usa curl para evitar problemas de certificados SSL en algunas instalaciones locales de Python.
comando = ['curl', '--ssl-no-revoke', '-L', '--fail', '-o', str(db_path), url]
resultado = subprocess.run(comando, capture_output=True, text=True)

# En algunos entornos Linux/Colab, curl puede no necesitar --ssl-no-revoke.
if resultado.returncode != 0:
    comando = ['curl', '-L', '--fail', '-o', str(db_path), url]
    resultado = subprocess.run(comando, capture_output=True, text=True)

if resultado.returncode != 0:
    raise RuntimeError('No se pudo descargar la base de datos desde GitHub. Revisa tu conexi?n a Internet.')

if not db_path.exists() or db_path.stat().st_size == 0:
    raise RuntimeError('La base de datos se descarg? vac?a. Vuelve a ejecutar la celda.')

# Conectarse a la base de datos SQLite
conn = sqlite3.connect(db_path)
print('Base de datos de Dulce Migaja cargada correctamente.')

Base de datos de Dulce Migaja cargada correctamente.

### **Paso 0.1: ¿Qué contiene la base de datos?**

Antes de analizar la normalización, primero observa qué tablas existen en la base de datos y qué información guarda cada una. Este paso permite reconocer el contenido antes de interpretar las consultas.

In [ ]:
# Ver las tablas disponibles en la base de datos
tablas = pd.read_sql_query(
'''
SELECT name AS tabla
FROM sqlite_schema
WHERE type = 'table'
AND name NOT LIKE 'sqlite_%'
ORDER BY name
''',
conn
)

display(tablas)

             tabla
0       categorias
1         clientes
2          locales
3        productos
4           ventas
5  ventas_original

### **Paso 0.2: Vista rápida de cada tabla**

Ejecuta estas celdas para observar algunos registros de cada tabla. No necesitas modificar el código; solo revisa qué datos aparecen.

In [ ]:
# Tabla original desnormalizada
pd.read_sql_query('SELECT * FROM ventas_original LIMIT 5', conn)

,id_venta,fecha,cliente_nombre,cliente_distrito,producto_nombre,categoria_nombre,local_nombre,local_distrito,cantidad,precio_unitario,metodo_pago,total_venta
0,1,2026-04-01,Ana Torres,Los Olivos,Pan frances,Panes,Panaderia Central,Los Olivos,20,0.5,Efectivo,10.0
1,2,2026-04-01,Luis Ramos,Comas,Empanada de pollo,Salados,Panaderia Norte,Comas,4,4.5,Yape,18.0
2,3,2026-04-01,Maria Perez,Independencia,Jugo de naranja,Bebidas,Panaderia Plaza,Independencia,2,5.0,Tarjeta,10.0
3,4,2026-04-02,Ana Torres,Los Olivos,Torta de chocolate,Pasteles,Panaderia Central,Los Olivos,1,8.0,Tarjeta,8.0
4,5,2026-04-02,Carlos Rios,San Martin de Porres,Pan integral,Panes,Panaderia Norte,Comas,12,0.8,Efectivo,9.6

In [ ]:
# Tablas normalizadas: categorias y productos
display(pd.read_sql_query('SELECT * FROM categorias', conn))
display(pd.read_sql_query('SELECT * FROM productos LIMIT 5', conn))

   id_categoria    nombre
0             1     Panes
1             2  Pasteles
2             3   Bebidas
3             4   Salados

   id_producto              nombre  id_categoria  precio_unitario
0            1         Pan frances             1              0.5
1            2        Pan integral             1              0.8
2            3   Empanada de pollo             4              4.5
3            4  Torta de chocolate             2              8.0
4            5     Jugo de naranja             3              5.0

In [ ]:
# Tablas normalizadas: clientes, locales y ventas
display(pd.read_sql_query('SELECT * FROM clientes LIMIT 5', conn))
display(pd.read_sql_query('SELECT * FROM locales', conn))
display(pd.read_sql_query('SELECT * FROM ventas LIMIT 5', conn))

   id_cliente       nombre              distrito
0           1   Ana Torres            Los Olivos
1           2   Luis Ramos                 Comas
2           3  Maria Perez         Independencia
3           4  Carlos Rios  San Martin de Porres
4           5    Rosa Diaz            Los Olivos

   id_local             nombre       distrito
0         1  Panaderia Central     Los Olivos
1         2    Panaderia Norte          Comas
2         3    Panaderia Plaza  Independencia

,id_venta,fecha,id_cliente,id_producto,id_local,cantidad,metodo_pago
0,1,2026-04-01,1,1,1,20,Efectivo
1,2,2026-04-01,2,3,2,4,Yape
2,3,2026-04-01,3,5,3,2,Tarjeta
3,4,2026-04-02,1,4,1,1,Tarjeta
4,5,2026-04-02,4,2,2,12,Efectivo

### **Paso 1: La tabla original — así guardaba Dulce Migaja sus ventas**

Antes de la normalización, todos los datos de cada venta se almacenaban en una sola tabla. Observa qué columnas tiene y qué información se repite.

In [ ]:
# Ver los primeros registros de la tabla original desnormalizada
df_original = pd.read_sql_query(
    'SELECT * FROM ventas_original LIMIT 15',
    conn
)
display(df_original)

,id_venta,fecha,cliente_nombre,cliente_distrito,producto_nombre,categoria_nombre,local_nombre,local_distrito,cantidad,precio_unitario,metodo_pago,total_venta
0,1,2026-04-01,Ana Torres,Los Olivos,Pan frances,Panes,Panaderia Central,Los Olivos,20,0.5,Efectivo,10.0
1,2,2026-04-01,Luis Ramos,Comas,Empanada de pollo,Salados,Panaderia Norte,Comas,4,4.5,Yape,18.0
2,3,2026-04-01,Maria Perez,Independencia,Jugo de naranja,Bebidas,Panaderia Plaza,Independencia,2,5.0,Tarjeta,10.0
3,4,2026-04-02,Ana Torres,Los Olivos,Torta de chocolate,Pasteles,Panaderia Central,Los Olivos,1,8.0,Tarjeta,8.0
4,5,2026-04-02,Carlos Rios,San Martin de Porres,Pan integral,Panes,Panaderia Norte,Comas,12,0.8,Efectivo,9.6
5,6,2026-04-02,Rosa Diaz,Los Olivos,Cafe americano,Bebidas,Panaderia Central,Los Olivos,3,4.0,Yape,12.0
6,7,2026-04-03,Luis Ramos,Comas,Pan frances,Panes,Panaderia Norte,Comas,15,0.5,Efectivo,7.5
7,8,2026-04-03,Jorge Salas,Comas,Empanada de pollo,Salados,Panaderia Plaza,Independencia,2,4.5,Yape,9.0
8,9,2026-04-03,Maria Perez,Independencia,Torta de chocolate,Pasteles,Panaderia Plaza,Independencia,2,8.0,Tarjeta,16.0
9,10,2026-04-04,Carlos Rios,San Martin de Porres,Jugo de naranja,Bebidas,Panaderia Norte,Comas,4,5.0,Yape,20.0
10,11,2026-04-04,Rosa Diaz,Los Olivos,Pan frances,Panes,Panaderia Central,Los Olivos,25,0.5,Efectivo,12.5
11,12,2026-04-04,Jorge Salas,Comas,Pan integral,Panes,Panaderia Plaza,Independencia,10,0.8,Tarjeta,8.0
12,13,2026-04-05,Ana Torres,Los Olivos,Empanada de pollo,Salados,Panaderia Central,Los Olivos,3,4.5,Efectivo,13.5
13,14,2026-04-05,Luis Ramos,Comas,Cafe americano,Bebidas,Panaderia Norte,Comas,2,4.0,Yape,8.0
14,15,2026-04-05,Maria Perez,Independencia,Pan frances,Panes,Panaderia Plaza,Independencia,18,0.5,Efectivo,9.0

**Pregunta 1:**
¿Qué columnas de `ventas_original` se repiten en varias filas? Menciona dos ejemplos concretos y explica qué problema genera esa repetición para el negocio.

Respuesta:
_______________________________________________________________________

### **Paso 2: ¿Cuántas veces se repite la información?**

Para ver la magnitud del problema, cuenta cuántas veces aparece cada cliente y cada categoría en la tabla original. Esto muestra exactamente cuántos registros habría que actualizar si cambia un dato.

In [ ]:
# Cuantas veces se repite cada cliente en la tabla original
df_rep_cli = pd.read_sql_query(
    '''
    SELECT cliente_nombre, COUNT(*) AS veces_repetido
    FROM ventas_original
    GROUP BY cliente_nombre
    ORDER BY veces_repetido DESC
    LIMIT 10
    ''',
    conn
)
display(df_rep_cli)

# Cuantas veces se repite cada categoria
df_rep_cat = pd.read_sql_query(
    '''
    SELECT categoria_nombre, COUNT(*) AS veces_repetido
    FROM ventas_original
    GROUP BY categoria_nombre
    ORDER BY veces_repetido DESC
    ''',
    conn
)
display(df_rep_cat)

  cliente_nombre  veces_repetido
0      Rosa Diaz               3
1    Maria Perez               3
2     Luis Ramos               3
3    Jorge Salas               3
4    Carlos Rios               3
5     Ana Torres               3

  categoria_nombre  veces_repetido
0            Panes               6
1          Bebidas               5
2          Salados               4
3         Pasteles               3

**Pregunta 2:**
¿Cuántas veces aparece el cliente más repetido? Si ese cliente cambiara su número de teléfono, ¿cuántos registros tendría que actualizar el administrador en la tabla original? ¿Qué soluciona la normalización?

Respuesta:
_______________________________________________________________________

### **Paso 3: Las tablas normalizadas — categorias y productos**

Ahora observa cómo quedaron los datos después de la normalización. La tabla `categorias` guarda cada categoría una sola vez (cumple **1FN** y **3FN**). La tabla `productos` usa `id_categoria` como clave foránea en lugar de repetir el texto de la categoría (elimina dependencia transitiva → **3FN**).

In [ ]:
# Tabla de categorias: cada categoria una sola vez
df_cat = pd.read_sql_query('SELECT * FROM categorias', conn)
display(df_cat)

   id_categoria    nombre
0             1     Panes
1             2  Pasteles
2             3   Bebidas
3             4   Salados

In [ ]:
# Tabla de productos: usa id_categoria como FK en vez de texto repetido
df_prod = pd.read_sql_query('SELECT * FROM productos', conn)
display(df_prod)

   id_producto              nombre  id_categoria  precio_unitario
0            1         Pan frances             1              0.5
1            2        Pan integral             1              0.8
2            3   Empanada de pollo             4              4.5
3            4  Torta de chocolate             2              8.0
4            5     Jugo de naranja             3              5.0
5            6      Cafe americano             3              4.0

**Pregunta 3:**
¿Cuántas categorías distintas existen? ¿Qué columna de `productos` actúa como clave foránea? Si cambia el nombre de una categoría, ¿en cuántos lugares habría que actualizarlo con este diseño normalizado?

Respuesta:
_______________________________________________________________________

### **Paso 4: Clientes, locales y la tabla ventas normalizada**

Las tablas `clientes` y `locales` guardan cada entidad una sola vez (**1FN** y **2FN**). La tabla `ventas` normalizada ya no repite nombres: solo almacena `id_cliente`, `id_producto` e `id_local`. Esto cumple la **2FN** porque todos los atributos dependen completamente de `id_venta` (la clave primaria).

In [ ]:
# Tabla de clientes
df_cli = pd.read_sql_query('SELECT * FROM clientes', conn)
display(df_cli)

   id_cliente       nombre              distrito
0           1   Ana Torres            Los Olivos
1           2   Luis Ramos                 Comas
2           3  Maria Perez         Independencia
3           4  Carlos Rios  San Martin de Porres
4           5    Rosa Diaz            Los Olivos
5           6  Jorge Salas                 Comas

In [ ]:
# Tabla de locales
df_loc = pd.read_sql_query('SELECT * FROM locales', conn)
display(df_loc)

   id_local             nombre       distrito
0         1  Panaderia Central     Los Olivos
1         2    Panaderia Norte          Comas
2         3    Panaderia Plaza  Independencia

In [ ]:
# Tabla de ventas normalizada
df_ven = pd.read_sql_query('SELECT * FROM ventas LIMIT 10', conn)
display(df_ven)

,id_venta,fecha,id_cliente,id_producto,id_local,cantidad,metodo_pago
0,1,2026-04-01,1,1,1,20,Efectivo
1,2,2026-04-01,2,3,2,4,Yape
2,3,2026-04-01,3,5,3,2,Tarjeta
3,4,2026-04-02,1,4,1,1,Tarjeta
4,5,2026-04-02,4,2,2,12,Efectivo
5,6,2026-04-02,5,6,1,3,Yape
6,7,2026-04-03,2,1,2,15,Efectivo
7,8,2026-04-03,6,3,3,2,Yape
8,9,2026-04-03,3,4,3,2,Tarjeta
9,10,2026-04-04,4,5,2,4,Yape

**Pregunta 4:**
¿Qué diferencia principal observas entre `ventas_original` y `ventas`? ¿Por qué la tabla `ventas` normalizada solo contiene números (IDs) en lugar de nombres? ¿Qué forma normal garantiza esto?

Respuesta:
_______________________________________________________________________

### **Paso 5: ¿Qué producto tiene el precio más alto?**

El dueño quiere revisar los productos ordenados por precio para analizar su política de precios.

In [ ]:
# Productos ordenados de mayor a menor precio
df_precio = pd.read_sql_query(
    '''
    SELECT nombre AS producto, precio_unitario
    FROM productos
    ORDER BY precio_unitario DESC
    ''',
    conn
)
display(df_precio)

             producto  precio_unitario
0  Torta de chocolate              8.0
1     Jugo de naranja              5.0
2   Empanada de pollo              4.5
3      Cafe americano              4.0
4        Pan integral              0.8
5         Pan frances              0.5

**Pregunta 5:**
¿Qué producto tiene el mayor precio unitario? ¿Y el menor? ¿Qué diferencia hay entre ambos precios?

Respuesta:
_______________________________________________________________________

### **Paso 6: ¿Cuántas ventas tiene cada categoría?**

La administradora quiere saber qué categoría concentra más ventas para decidir qué producir más.

In [ ]:
# Ventas totales por categoria (usando la tabla original para ver el dato directo)
df_cat_ven = pd.read_sql_query(
    '''
    SELECT categoria_nombre, COUNT(*) AS total_ventas
    FROM ventas_original
    GROUP BY categoria_nombre
    ORDER BY total_ventas DESC
    ''',
    conn
)
display(df_cat_ven)

  categoria_nombre  total_ventas
0            Panes             6
1          Bebidas             5
2          Salados             4
3         Pasteles             3

**Pregunta 6:**
¿Qué categoría tiene más ventas registradas? ¿Qué recomendarías al equipo de producción basándote en este resultado?

Respuesta:
_______________________________________________________________________

### **Paso 7: ¿Qué local registra más ventas?**

El gerente quiere identificar el local con mayor actividad para reforzarlo con más personal. Aquí se usa JOIN para obtener el nombre del local en lugar del ID.

In [ ]:
# Ventas por local: se usa JOIN para obtener el nombre del local
df_loc_ven = pd.read_sql_query(
    '''
    SELECT l.nombre AS local, COUNT(*) AS total_ventas
    FROM ventas v
    INNER JOIN locales l ON v.id_local = l.id_local
    GROUP BY l.id_local, l.nombre
    ORDER BY total_ventas DESC
    ''',
    conn
)
display(df_loc_ven)

               local  total_ventas
0  Panaderia Central             6
1    Panaderia Norte             6
2    Panaderia Plaza             6

**Pregunta 7:**
¿Qué local registra más ventas? ¿Por qué fue necesario usar JOIN en lugar de consultar solo la tabla `ventas`?

Respuesta:
_______________________________________________________________________

### **Paso 8: Reporte completo de ventas con JOIN**

Para obtener un reporte legible — con nombres en lugar de números — se combinan las tablas normalizadas. Esto es exactamente lo que hace el JOIN: conecta las tablas usando las claves foráneas.

In [ ]:
# Reporte completo: nombre del cliente, producto, local y monto
df_reporte = pd.read_sql_query(
    '''
    SELECT
        v.id_venta,
        c.nombre AS cliente,
        p.nombre AS producto,
        l.nombre AS local,
        v.cantidad,
        p.precio_unitario,
        ROUND(v.cantidad * p.precio_unitario, 2) AS total_venta
    FROM ventas v
    INNER JOIN clientes  c ON v.id_cliente  = c.id_cliente
    INNER JOIN productos p ON v.id_producto = p.id_producto
    INNER JOIN locales   l ON v.id_local    = l.id_local
    ORDER BY total_venta DESC
    LIMIT 12
    ''',
    conn
)
display(df_reporte)

,id_venta,cliente,producto,local,cantidad,precio_unitario,total_venta
0,10,Carlos Rios,Jugo de naranja,Panaderia Norte,4,5.0,20.0
1,2,Luis Ramos,Empanada de pollo,Panaderia Norte,4,4.5,18.0
2,18,Jorge Salas,Empanada de pollo,Panaderia Plaza,4,4.5,18.0
3,9,Maria Perez,Torta de chocolate,Panaderia Plaza,2,8.0,16.0
4,13,Ana Torres,Empanada de pollo,Panaderia Central,3,4.5,13.5
5,11,Rosa Diaz,Pan frances,Panaderia Central,25,0.5,12.5
6,6,Rosa Diaz,Cafe americano,Panaderia Central,3,4.0,12.0
7,1,Ana Torres,Pan frances,Panaderia Central,20,0.5,10.0
8,3,Maria Perez,Jugo de naranja,Panaderia Plaza,2,5.0,10.0
9,17,Rosa Diaz,Jugo de naranja,Panaderia Central,2,5.0,10.0
10,5,Carlos Rios,Pan integral,Panaderia Norte,12,0.8,9.6
11,8,Jorge Salas,Empanada de pollo,Panaderia Plaza,2,4.5,9.0

**Pregunta 8:**
¿Por qué fue necesario usar tres JOIN para generar este reporte? ¿Qué ventaja tiene hacer JOIN sobre una base normalizada frente a guardar todo en `ventas_original`?

Respuesta:
_______________________________________________________________________

### **Paso 9: ¿Qué cliente compra con más frecuencia?**

Marketing quiere identificar a los clientes más frecuentes para ofrecerles una tarjeta de fidelización.

In [ ]:
# Top 5 clientes con mas compras
df_top_cli = pd.read_sql_query(
    '''
    SELECT c.nombre AS cliente, COUNT(*) AS total_compras
    FROM ventas v
    INNER JOIN clientes c ON v.id_cliente = c.id_cliente
    GROUP BY c.id_cliente, c.nombre
    ORDER BY total_compras DESC
    LIMIT 5
    ''',
    conn
)
display(df_top_cli)

       cliente  total_compras
0   Ana Torres              3
1   Luis Ramos              3
2  Maria Perez              3
3  Carlos Rios              3
4    Rosa Diaz              3

**Pregunta 9:**
¿Quién es el cliente más frecuente? ¿Qué acción concreta de marketing podría implementar Dulce Migaja para retenerlo?

Respuesta:
_______________________________________________________________________

### **Paso 10: ¿Qué producto genera más ingresos?**

El dueño quiere saber qué productos son los más rentables en términos de ingresos totales.

In [ ]:
# Ingresos totales por producto
df_ingresos = pd.read_sql_query(
    '''
    SELECT
        p.nombre AS producto,
        COUNT(*) AS veces_vendido,
        SUM(v.cantidad) AS unidades_totales,
        ROUND(SUM(v.cantidad * p.precio_unitario), 2) AS ingresos_totales
    FROM ventas v
    INNER JOIN productos p ON v.id_producto = p.id_producto
    GROUP BY p.id_producto, p.nombre
    ORDER BY ingresos_totales DESC
    ''',
    conn
)
display(df_ingresos)

             producto  veces_vendido  unidades_totales  ingresos_totales
0   Empanada de pollo              4                13              58.5
1     Jugo de naranja              3                 8              40.0
2         Pan frances              4                78              39.0
3  Torta de chocolate              3                 4              32.0
4      Cafe americano              2                 5              20.0
5        Pan integral              2                22              17.6

**Pregunta 10:**
¿Qué producto genera más ingresos totales? ¿Coincide con el producto más caro del Paso 5? ¿Qué conclusión puedes extraer sobre precio vs. volumen de ventas?

Respuesta:
_______________________________________________________________________

---
## **ACTIVIDAD 3: Aplicación y Reflexión**

Responde las siguientes preguntas **sin ejecutar código**. Usa tu comprensión del modelo normalizado de Dulce Migaja y los resultados obtenidos en la Actividad 2. Escribe respuestas en párrafos completos, no en listas.

---

**Situación 1:**
El dueño de Dulce Migaja decide que cada producto puede pertenecer a **más de una categoría** (por ejemplo, 'Pan de chocolate' podría ser 'Panadería' y 'Postres' al mismo tiempo).

¿La estructura actual de las tablas `productos` y `categorias` soporta este cambio? ¿Qué forma normal se vería afectada? ¿Qué tabla nueva habría que crear?

Respuesta:
_______________________________________________________________________

**Situación 2:**
Un desarrollador nuevo propone agregar directamente las columnas `nombre_cliente`, `telefono_cliente` y `direccion_cliente` a la tabla `ventas` para evitar el JOIN.

¿Qué forma normal se violaría con esta decisión? ¿Qué problemas concretos generaría para Dulce Migaja cuando un cliente cambie su dirección?

Respuesta:
_______________________________________________________________________

**Situación 3:**
La panadería quiere expandirse y comenzar a ofrecer **delivery**. Para eso necesita registrar: dirección de entrega, hora estimada de llegada, nombre del repartidor y costo del envío.

¿La estructura actual soporta este nuevo requerimiento? ¿Qué tabla o tablas nuevas crearías? Describe brevemente las columnas que tendría cada tabla nueva.

Respuesta:
_______________________________________________________________________

**Situación 4:**
La tabla `productos` tiene una columna llamada `id_categoria` (clave foránea). Imagina que en cambio hubiera una columna `nombre_categoria` de tipo texto (como en `ventas_original`).

¿Qué dependencia transitiva existiría? ¿Qué forma normal se violaría? ¿Qué pasaría si se cambiara el nombre de una categoría?

Respuesta:
_______________________________________________________________________

**Situación 5 — Integración:**
Basándote en todo lo explorado en este laboratorio, explica con tus propias palabras por qué Dulce Migaja tomó la decisión correcta al normalizar su base de datos. Menciona al menos **tres beneficios concretos** que obtiene el negocio con el diseño normalizado frente a la tabla `ventas_original`.

Respuesta:
_______________________________________________________________________

---
## **Conclusiones**

Escribe cinco conclusiones sobre lo aprendido en este laboratorio:

**1.** _¿Qué problema concreto resuelve la 1FN, la 2FN y la 3FN?_

**2.** _¿Qué diferencia fundamental existe entre la tabla `ventas_original` y el diseño normalizado?_

**3.** _¿Para qué sirve el JOIN y en qué situaciones lo usarías en el negocio de Dulce Migaja?_

**4.** _¿Qué consulta SQL de la Actividad 2 te resultó más útil para la toma de decisiones?_

**5.** _¿Por qué es más fácil mantener y actualizar una base de datos normalizada?_

---
**© 2026 - Fundamentos de Gestión de Datos - TECSUP**  
**Docente:** Pilar Rocío Sayán Mejía